src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=CommentsRepository::class)
 */
class Comments
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="boolean", nullable = true)
     */
    private $actif;

    /**
     * @ORM\Column(type="boolean")
     */
    private $rgpd = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getRgpd(): ?bool
    {
        return $this->rgpd;
    }

    public function setRgpd(bool $rgpd): self
    {
        $this->rgpd = $rgpd;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/AboutUsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AboutUsController extends AbstractController
{
    /**
     * @Route("/about", name="about_us")
     */
    public function index(): Response
    {
        return $this->render('about_us/index.html.twig');
    }
}

templates/about_us/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}La boutique{% endblock %}


{% block content %}

    {################ Où nous trouver ################}
    <h2 class="mb-3 text-center">Où nous trouver ?</h2>
    <div id="map" class="map"></div>   
    <div id="marker" title="Marker"></div>

    {################ Images ################}
    <h2 class="mb-3 text-center mt-5">Le magasin</h2>
    <div class="col-md-6 m-auto">
        <img  src="{{ asset('assets/img/magasin.jpg') }}" class="mt-3 zoom img-fluid"  alt="">
    </div>
    <div class="mt-5 row">
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <img  src="{{ asset('assets/img/img1-contact.jpg') }}" class="mt-3 zoom img-fluid"  alt="">
            </a>
        </div>

        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <img  src="{{ asset('assets/img/img2-contact.jpg') }}" class="mt-3 zoom img-fluid"  alt="">
            </a>
        </div>
        
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <img  src="{{ asset('assets/img/img3-contact.jpg') }}" class="mt-3 zoom img-fluid "  alt="">
            </a>
        </div>
        
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <img  src="{{ asset('assets/img/img4-contact.jpg') }}" class="mt-3 zoom img-fluid "  alt="">
            </a>
        </div>
    </div>

    {################ Contactez-nous ################}
    <div class="mt-5 mb-5 text-center">
        <h2>Contactez-nous</h2>
        <br>
        <div class="mt-2">
            <i class="iconContact fas fa-phone"></i>
            <br>
            <strong>
                +33 (0) 1 53 81 73 07 
            </strong>
        </div>

        <div class="mt-2">
            <i class="iconContact fas fa-envelope">
                <a href="{{ path('contact') }}"></a>
            </i>
            <br>
            Ecrivez nous un message
        </div>

        <div class="mt-2">
            <i class="iconContact fas fa-map-marker"></i>
            <br>
            55 boulevard des Alpes, 05100 Les Alpes</div>
        </div>
    </div>

    {################ Services ################}
    
    <h2 class="mt-2 text-center">Nos services</h2>

    <div class="ml-4 mr-4 row mt-3 mb-5 text-center">
        <div class="card mt-3 col-md-3">
            <i class="iconServices fas fa-comment-alt"></i>
            <h3>Contact</h3>
            <strong>+33 (0) 1 53 81 73 07</strong>
        </div>

        <div class="card mt-3 col-md-3">
            <i class="iconServices fas fa-truck"></i>
            <h3>Livraison rapide</h3>
            <strong>Vos skis livrés en un clin d'oeil</strong>
        </div>

        <div class="card mt-3 col-md-3">
            <i class="iconServices far fa-credit-card"></i>
            <h3>Paiement sécurisé</h3>
            <strong>Stripe payments</strong>
        </div>

        <div class="card text-center mt-3 col-md-3">
            <i class="iconServices fas fa-thumbs-up"></i>
            <h3>Satisfait ou remboursé</h3>
            <strong>Sous 15 jours</strong>
        </div>
    </div>

    {################ Formulaire d'ajout de commentaires ################}
    <div class="container text-center">
        {% if (is_granted("ROLE_USER") or is_granted("ROLE_ADMIN")) %}
            {{ form(form) }}
        {% endif %}
    </div>

    {% for comment in app.flashes('success') %}
        <div class="mt-5 container alert alert-success">
            {{ comment }}
        </div>
    {% endfor %}

    {################ Liste des commentaires ################}
    <div class="mb-5 mt-5 container text-center">
    
        <h2 class="mb-3">Vos commentaires</h2>


        {% if liste_commentaires is empty %}

            <p style="font-style: italic">Il n'y a pas de commentaires</p>

         {% else %}

            {% for commentaire in liste_commentaires %}
                    {% if commentaire.actif == 1 %}
                        <p style="font-style: italic">Commentaire ajouté par {{ commentaire.user.firstname }} le {{ commentaire.createdAt|date('d-m-Y à h:i:s') }}</p>
                        <p>{{ commentaire.content }}</p>
                        <hr>
                    {% endif %}

            {% endfor %}

        {% endif %}

    </div>
                   
{% endblock %}